#pragma once

// Observation: everything the planner measures, gathered from the catalog.
//
// This is the only file that talks to a database on the planning path, and
// that is deliberate: planner.h is a pure function of (Spec, Observations), so
// plan determinism can be tested against a fixed struct with no server in the
// loop. Anything the planner needs must arrive through Observations.
//
// The JSON is built in SQL rather than in C++ -- one SELECT JSONB_BUILD_OBJECT
// per concern, one row, one column, parsed on arrival. It removes essentially
// all marshalling code, and it is pg_licht's dominant pattern for the same
// reason.

#include <optional>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

#include "observations.h"
#include "planner_base.h"  // quote_identifier, and nothing that reaches pqxx
#include "session.h"

namespace pglaswell {

using json = nlohmann::json;


namespace detail {

// One statement, all the per-table structure and statistics the planner reads.
//
// size_estimate is relpages*8192 -- free, and only as fresh as estimated_from
// says. The measured size (pg_table_size) is NOT taken here: it opens the
// relation with AccessShareLock, so during a rewrite it queues behind the
// ALTER TABLE. Escalation to it is a separate, conditional call below, which
// keeps the lock hazard in one place with one reason.
inline const char* kTableObservationSql = R"SQL(
WITH target AS (
  SELECT c.oid, c.relname, c.relkind, c.relispartition, c.reltuples, c.relpages,
         c.reloptions, c.relowner, c.relacl,
         c.relrowsecurity, c.relforcerowsecurity, n.nspname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = $1 AND c.relname = $2
)
SELECT COALESCE(
  (SELECT JSONB_BUILD_OBJECT(
     'exists', true,
     'kind', CASE t.relkind WHEN 'r' THEN 'table'
                            WHEN 'p' THEN 'partitioned_table'
                            WHEN 'm' THEN 'materialized_view'
                            WHEN 'v' THEN 'view'
                            ELSE t.relkind::text END,
     -- Only meaningful when 'kind' is view or materialized_view, and needed
     -- because replace_view must restore what CREATE OR REPLACE resets.
     'view_definition', CASE WHEN t.relkind IN ('v','m')
                             THEN PG_GET_VIEWDEF(t.oid, true) END,
     'reloptions', COALESCE(TO_JSONB(t.reloptions), '[]'::jsonb),
     'owner', PG_GET_USERBYID(t.relowner),
     'is_partition', t.relispartition,
     'reltuples', GREATEST(t.reltuples, 0)::bigint,
     'size_estimate', (t.relpages::bigint * 8192),
     'estimated_from', (SELECT GREATEST(s.last_vacuum, s.last_autovacuum,
                                        s.last_analyze, s.last_autoanalyze)
                          FROM pg_stat_all_tables s WHERE s.relid = t.oid),
     'stats', (SELECT JSONB_BUILD_OBJECT(
                 'n_live_tup', s.n_live_tup, 'n_dead_tup', s.n_dead_tup,
                 'n_mod_since_analyze', s.n_mod_since_analyze,
                 'seq_scan', s.seq_scan, 'idx_scan', s.idx_scan,
                 'n_tup_ins', s.n_tup_ins, 'n_tup_upd', s.n_tup_upd,
                 'n_tup_del', s.n_tup_del)
                 FROM pg_stat_all_tables s WHERE s.relid = t.oid),
     'columns', COALESCE((SELECT JSONB_OBJECT_AGG(a.attname, JSONB_BUILD_OBJECT(
                   'type_oid', a.atttypid::bigint,
                   'type', format_type(a.atttypid, a.atttypmod),
                   'not_null', a.attnotnull,
                   'has_default', a.atthasdef,
                   -- What a row-level INSERT is allowed to say about this
                   -- column. Measured (S21) on 18.6, all three refusals are
                   -- errors PostgreSQL raises at execution and the planner can
                   -- raise beforehand instead:
                   --
                   --   attidentity 'a'  GENERATED ALWAYS -- naming it is an
                   --                    error unless the statement carries
                   --                    OVERRIDING SYSTEM VALUE
                   --   attidentity 'd'  GENERATED BY DEFAULT -- naming it is
                   --                    allowed and leaves the sequence behind
                   --   attgenerated 's' STORED -- naming it is always an error
                   --
                   -- '' for an ordinary column, so the planner tests for the
                   -- letter rather than for presence.
                   'identity', a.attidentity::text,
                   'generated', a.attgenerated::text,
                   -- The sequence this column draws from, identity or serial,
                   -- schema-qualified. This is the one that decides a
                   -- correctness bug rather than an error message: inserting
                   -- explicit ids does NOT advance the sequence (S21 measured
                   -- last_value still unset after five explicit rows), so the
                   -- application's next insert fails with a duplicate key --
                   -- after the migration reported success. NULL when the column
                   -- owns no sequence.
                   'sequence', PG_GET_SERIAL_SEQUENCE(
                                 FORMAT('%I.%I', t.nspname, t.relname), a.attname)))
                   FROM pg_attribute a
                  WHERE a.attrelid = t.oid AND a.attnum > 0 AND NOT a.attisdropped),
                 '{}'::jsonb),
     'indexes', COALESCE((SELECT JSONB_OBJECT_AGG(ic.relname, JSONB_BUILD_OBJECT(
                   'is_valid', i.indisvalid,
                   'is_ready', i.indisready,
                   'is_unique', i.indisunique,
                   'is_primary', i.indisprimary,
                   'definition', pg_get_indexdef(i.indexrelid),
                   'method', am.amname,
                   'predicate', COALESCE(pg_get_expr(i.indpred, i.indrelid), ''),
                   -- Column names in index order. An expression column has
                   -- attnum 0 and cannot be named, so has_expressions marks the
                   -- index as one this tool must not reason about: comparing a
                   -- partial list would be worse than declining to compare.
                   'has_expressions', (0 = ANY(i.indkey)),
                   -- Renaming a constraint-backed index renames the CONSTRAINT
                   -- too (measured on 18.6: t_b_key -> t_b_renamed renamed the
                   -- UNIQUE constraint, and the same for a primary key). That
                   -- is a far larger change than adopting an index name, so
                   -- these are never renamed.
                   'constraint_backed', EXISTS (SELECT 1 FROM pg_constraint k
                                                 WHERE k.conindid = i.indexrelid),
                   'columns', (SELECT JSONB_AGG(a.attname ORDER BY k.ord)
                                 FROM unnest(i.indkey) WITH ORDINALITY AS k(attnum, ord)
                                 JOIN pg_attribute a ON a.attrelid = t.oid
                                                    AND a.attnum = k.attnum),
                   'leading_column', (SELECT a.attname FROM pg_attribute a
                                       WHERE a.attrelid = t.oid
                                         AND a.attnum = i.indkey[0])))
                   FROM pg_index i
                   JOIN pg_class ic ON ic.oid = i.indexrelid
                   JOIN pg_am am ON am.oid = ic.relam
                  WHERE i.indrelid = t.oid),
                 '{}'::jsonb),
     -- Row-level security, its policies, and the table's own triggers.
     --
     -- relrowsecurity alone is not the whole answer: measured on 18.6, an
     -- owner BYPASSES RLS unless relforcerowsecurity is also set, and a
     -- superuser bypasses it whatever either flag says. Both are recorded so
     -- the planner can say which of those a reader is about to be fooled by.
     'row_security', JSONB_BUILD_OBJECT(
        'enabled', t.relrowsecurity, 'forced', t.relforcerowsecurity),
     'policies', COALESCE((
        SELECT JSONB_OBJECT_AGG(pol.polname, JSONB_BUILD_OBJECT(
                 'command', pol.polcmd::text,
                 'permissive', pol.polpermissive,
                 'roles', COALESCE((SELECT JSONB_AGG(PG_GET_USERBYID(r))
                                      FROM UNNEST(pol.polroles) AS r), '[]'::jsonb),
                 'using', PG_GET_EXPR(pol.polqual, pol.polrelid),
                 'check', PG_GET_EXPR(pol.polwithcheck, pol.polrelid)))
          FROM pg_policy pol WHERE pol.polrelid = t.oid), '{}'::jsonb),
     'triggers', COALESCE((
        SELECT JSONB_OBJECT_AGG(tg.tgname, JSONB_BUILD_OBJECT(
                 -- tgenabled: O origin, D disabled, R replica, A always.
                 'enabled', tg.tgenabled = 'O' OR tg.tgenabled = 'A',
                 'state', tg.tgenabled::text,
                 'definition', PG_GET_TRIGGERDEF(tg.oid)))
          FROM pg_trigger tg
         WHERE tg.tgrelid = t.oid AND NOT tg.tgisinternal), '{}'::jsonb),
     'grants', COALESCE(TO_JSONB(t.relacl::text[]), '[]'::jsonb),
     -- Foreign keys pointing AT this table, from elsewhere.
     --
     -- The table's own constraints say what it depends on; this says what
     -- depends on it, and only this can answer whether a DROP will be refused.
     -- Measured (S17): DROP TABLE names the inbound constraint and stops.
     'referenced_by', COALESCE((
        SELECT JSONB_AGG(k.conname || ' on ' || k.conrelid::regclass::text
                         ORDER BY k.conname)
          FROM pg_constraint k
         WHERE k.contype = 'f' AND k.confrelid = t.oid), '[]'::jsonb),
     -- Views that read this table, transitively, with everything a rebuild
     -- has to put back.
     --
     -- This is an OBSERVATION rather than an intent kind because PostgreSQL
     -- refuses any type change on a column a view reads -- measured on 18.6,
     -- text -> varchar(200) is refused even though it rewrites nothing -- so a
     -- planner that cannot see the stack cannot plan the change at all.
     --
     -- Every field beyond 'definition' exists because dropping and recreating
     -- loses it silently. Measured, all eight: comment, per-column comments,
     -- grants, COLUMN-level grants, reloptions (security_barrier /
     -- security_invoker), INSTEAD OF triggers, a materialized view's indexes,
     -- and the owner. The rebuild is the easy half; the restore is the work.
     --
     -- 'level' is the depth: drop highest first, recreate in reverse.
     'dependent_views', COALESCE((
        WITH RECURSIVE deps AS (
          SELECT DISTINCT r.ev_class AS oid, 1 AS level
            FROM pg_depend d
            JOIN pg_rewrite r ON r.oid = d.objid AND r.ev_class <> d.refobjid
           WHERE d.refobjid = t.oid AND d.classid = 'pg_rewrite'::regclass
          UNION ALL
          SELECT DISTINCT r.ev_class, deps.level + 1
            FROM deps
            JOIN pg_depend d ON d.refobjid = deps.oid
                            AND d.classid = 'pg_rewrite'::regclass
            JOIN pg_rewrite r ON r.oid = d.objid AND r.ev_class <> d.refobjid
           WHERE deps.level < 32   -- a cycle is impossible, but a bound is cheap
        ), ranked AS (
          SELECT oid, MAX(level) AS level FROM deps GROUP BY oid
        )
        SELECT JSONB_OBJECT_AGG(vn.nspname || '.' || vc.relname, JSONB_BUILD_OBJECT(
          -- Always schema-qualified and quoted. oid::regclass::text omits the
          -- schema when it is on search_path, which reads fine in psql and is
          -- wrong the moment the text is used to GENERATE DDL: the recreate
          -- would land wherever search_path pointed at execution time.
          'name', FORMAT('%I.%I', vn.nspname, vc.relname),
          'level', ranked.level,
          'kind', CASE vc.relkind WHEN 'm' THEN 'materialized' ELSE 'view' END,
          'definition', PG_GET_VIEWDEF(vc.oid, true),
          'owner', PG_GET_USERBYID(vc.relowner),
          'comment', OBJ_DESCRIPTION(vc.oid, 'pg_class'),
          'reloptions', COALESCE(TO_JSONB(vc.reloptions), '[]'::jsonb),
          -- Columns this view reads FROM THE TARGET TABLE. A view touching a
          -- column nobody is changing does not need rebuilding, and rebuilding
          -- it anyway would widen the blast radius for nothing.
          'uses_columns', COALESCE((
             SELECT JSONB_AGG(DISTINCT a.attname)
               FROM pg_depend dd
               JOIN pg_rewrite rr ON rr.oid = dd.objid AND rr.ev_class = vc.oid
               JOIN pg_attribute a ON a.attrelid = dd.refobjid
                                  AND a.attnum = dd.refobjsubid
              WHERE dd.refobjid = t.oid AND dd.refobjsubid > 0), '[]'::jsonb),
          -- Which OTHER dependent views this one reads directly.
          --
          -- Depth alone cannot answer "does this view come down with that
          -- one": two views can sit at the same level and be entirely
          -- unrelated, and rebuilding the innocent one widens the blast radius
          -- for nothing. The planner needs real edges to walk, so it gets them.
          'depends_on', COALESCE((
             SELECT JSONB_AGG(DISTINCT rn.nspname || '.' || rc.relname)
               FROM pg_depend dd
               JOIN pg_rewrite rr ON rr.oid = dd.objid AND rr.ev_class = vc.oid
               JOIN pg_class rc ON rc.oid = dd.refobjid
                                AND rc.relkind IN ('v', 'm')
               JOIN pg_namespace rn ON rn.oid = rc.relnamespace
              WHERE dd.refobjid <> vc.oid), '[]'::jsonb),
          'column_comments', COALESCE((
             SELECT JSONB_OBJECT_AGG(a.attname, col_description(vc.oid, a.attnum))
               FROM pg_attribute a
              WHERE a.attrelid = vc.oid AND a.attnum > 0 AND NOT a.attisdropped
                AND col_description(vc.oid, a.attnum) IS NOT NULL), '{}'::jsonb),
          'grants', COALESCE(TO_JSONB(vc.relacl::text[]), '[]'::jsonb),
          'column_grants', COALESCE((
             SELECT JSONB_AGG(DISTINCT JSONB_BUILD_OBJECT(
                      'column', a.attname, 'acl', a.attacl::text[]))
               FROM pg_attribute a
              WHERE a.attrelid = vc.oid AND a.attacl IS NOT NULL), '[]'::jsonb),
          'triggers', COALESCE((
             SELECT JSONB_AGG(PG_GET_TRIGGERDEF(tg.oid))
               FROM pg_trigger tg
              WHERE tg.tgrelid = vc.oid AND NOT tg.tgisinternal), '[]'::jsonb),
          'indexes', COALESCE((
             SELECT JSONB_AGG(PG_GET_INDEXDEF(ix.indexrelid))
               FROM pg_index ix WHERE ix.indrelid = vc.oid), '[]'::jsonb)))
          FROM ranked JOIN pg_class vc ON vc.oid = ranked.oid
               JOIN pg_namespace vn ON vn.oid = vc.relnamespace), '{}'::jsonb),
     -- Constraints, with what would break if one were dropped. PostgreSQL
     -- refuses to drop a unique constraint a foreign key depends on, and the
     -- dependency is visible beforehand through the shared index: refusing in
     -- the planner beats failing at execution.
     'constraints', COALESCE((SELECT JSONB_OBJECT_AGG(k.conname, JSONB_BUILD_OBJECT(
                       'type', k.contype::text,
                       'has_index', k.conindid <> 0,
                       'index', CASE WHEN k.conindid <> 0
                                     THEN k.conindid::regclass::text END,
                       'references', CASE WHEN k.contype = 'f'
                                          THEN k.confrelid::regclass::text END,
                       'column', (SELECT a.attname FROM pg_attribute a
                                   WHERE a.attrelid = t.oid
                                     AND a.attnum = k.conkey[1]),
                       'depended_on_by', COALESCE((
                          SELECT JSONB_AGG(d.conname || ' on ' ||
                                           d.conrelid::regclass::text)
                            FROM pg_constraint d
                           WHERE d.contype = 'f' AND k.conindid <> 0
                             AND d.conindid = k.conindid
                             AND d.oid <> k.oid), '[]'::jsonb)))
                       FROM pg_constraint k WHERE k.conrelid = t.oid), '{}'::jsonb),
     'lock_waiters', (SELECT COUNT(*) FROM pg_locks l
                       WHERE l.relation = t.oid AND NOT l.granted),
     -- Direct partitions, in name order so a plan is stable across runs.
     -- CREATE INDEX CONCURRENTLY is refused on a partitioned parent, so the
     -- planner needs the children to build on each of them instead.
     'partitions', COALESCE((SELECT JSONB_AGG(pn.nspname || '.' || pc.relname
                                              ORDER BY pn.nspname, pc.relname)
                               FROM pg_inherits pi
                               JOIN pg_class pc ON pc.oid = pi.inhrelid
                               JOIN pg_namespace pn ON pn.oid = pc.relnamespace
                              WHERE pi.inhparent = t.oid), '[]'::jsonb),
     -- Partition-key text, e.g. "RANGE (at)". The planner needs the key COLUMN
     -- to render the CHECK constraint that turns an ATTACH from a full scan
     -- into a catalog change (measured: 98ms vs 0.9ms on 2M rows).
     'partition_key', CASE WHEN t.relkind = 'p'
                           THEN PG_GET_PARTKEYDEF(t.oid) END,
     -- A DEFAULT partition has to be scanned on every ATTACH, to prove it
     -- holds no row belonging to the new bounds. That cost belongs to the
     -- DEFAULT, not to the candidate, so no CHECK on the candidate avoids it:
     -- measured at 165ms with a 2M-row default, against 0.9ms without one.
     'default_partition', (SELECT pn.nspname || '.' || pc.relname
                             FROM pg_inherits pi
                             JOIN pg_class pc ON pc.oid = pi.inhrelid
                             JOIN pg_namespace pn ON pn.oid = pc.relnamespace
                            WHERE pi.inhparent = t.oid
                              AND PG_GET_EXPR(pc.relpartbound, pc.oid) = 'DEFAULT'),
     -- A partition left half-detached by an interrupted DETACH CONCURRENTLY.
     -- It is still in pg_inherits, still reports relispartition, and only this
     -- flag says the cluster is mid-operation and needs FINALIZE.
     'detach_pending', COALESCE((SELECT JSONB_AGG(pn.nspname || '.' || pc.relname)
                               FROM pg_inherits pi
                               JOIN pg_class pc ON pc.oid = pi.inhrelid
                               JOIN pg_namespace pn ON pn.oid = pc.relnamespace
                              WHERE pi.inhparent = t.oid
                                AND pi.inhdetachpending), '[]'::jsonb),
     -- The parent's partitioned indexes. Anything here without a match on the
     -- candidate is BUILT during ATTACH, under AccessExclusiveLock on the
     -- candidate -- which is what made the first measurement of this recipe
     -- read as though a CHECK constraint bought nothing.
     'partitioned_indexes', COALESCE((
        SELECT JSONB_OBJECT_AGG(ic.relname,
                 PG_GET_INDEXDEF(i.indexrelid))
          FROM pg_index i
          JOIN pg_class ic ON ic.oid = i.indexrelid
         WHERE i.indrelid = t.oid AND ic.relkind = 'I'), '{}'::jsonb)
   ) FROM target t),
  JSONB_BUILD_OBJECT('exists', false))
)SQL";

// Everything that is not a relation, and -- for anything droppable -- what
// depends on it.
//
// The dependants are the point. Measured (spike S18, 18.6), PostgreSQL refuses
// to drop a type, a function or a sequence that anything uses, and names the
// dependant every time:
//
//   ERROR: cannot drop type mood because other objects depend on it
//   DETAIL: column m of table uses_mood depends on type mood
//
// pg_depend answers the same question beforehand, so the planner refuses
// precisely instead of letting execution fail with a hint suggesting CASCADE.
// One query per object, $1 = kind, $2 = name, $3 = schema (ignored where the
// object is not schema-qualified).
inline constexpr const char* kObjectObservationSql = R"SQL(
WITH target AS (
  SELECT CASE $1
    WHEN 'schema'    THEN (SELECT oid FROM pg_namespace WHERE nspname = $2)
    WHEN 'extension' THEN (SELECT oid FROM pg_extension WHERE extname = $2)
    WHEN 'type'      THEN (SELECT t.oid FROM pg_type t
                             JOIN pg_namespace n ON n.oid = t.typnamespace
                            WHERE t.typname = $2 AND n.nspname = $3)
    WHEN 'sequence'  THEN (SELECT c.oid FROM pg_class c
                             JOIN pg_namespace n ON n.oid = c.relnamespace
                            WHERE c.relname = $2 AND n.nspname = $3
                              AND c.relkind = 'S')
    WHEN 'function'  THEN (SELECT p.oid FROM pg_proc p
                             JOIN pg_namespace n ON n.oid = p.pronamespace
                            WHERE p.proname = $2 AND n.nspname = $3
                            ORDER BY p.oid LIMIT 1)
    END AS oid,
    CASE $1
      WHEN 'schema' THEN 'pg_namespace' WHEN 'extension' THEN 'pg_extension'
      WHEN 'type' THEN 'pg_type' WHEN 'function' THEN 'pg_proc'
      ELSE 'pg_class' END::regclass AS classid
)
SELECT COALESCE((
  SELECT JSONB_BUILD_OBJECT(
    'exists', true,
    'kind', $1,
    -- What would block a drop. pg_describe_object renders each dependant the
    -- way PostgreSQL's own error message does, so the refusal reads like the
    -- one the author would otherwise have hit.
    'depended_on_by', COALESCE((
       SELECT JSONB_AGG(DISTINCT PG_DESCRIBE_OBJECT(d.classid, d.objid, d.objsubid))
         FROM pg_depend d
        -- deptype 'n' (normal) ONLY. An 'a' (auto) dependency is dropped WITH
       -- the object rather than blocking it -- a domain's own CHECK
       -- constraints, a sequence owned by a column -- so counting those made
       -- pg_laswell refuse to drop any domain that had a constraint, which is
       -- very nearly every domain. Found by the conformance suite.
       WHERE d.refobjid = t.oid AND d.refclassid = t.classid
          AND d.deptype = 'n'
          AND NOT (d.classid = t.classid AND d.objid = t.oid)), '[]'::jsonb),
    -- Enum labels, so add_enum_value can report satisfied instead of failing
    -- on a duplicate, and so the plan can show the resulting order.
    'enum_labels', CASE WHEN $1 = 'type' THEN COALESCE((
       SELECT JSONB_AGG(e.enumlabel ORDER BY e.enumsortorder)
         FROM pg_enum e WHERE e.enumtypid = t.oid), '[]'::jsonb) END,
    'type_kind', CASE WHEN $1 = 'type' THEN
       (SELECT CASE ty.typtype WHEN 'e' THEN 'enum' WHEN 'd' THEN 'domain'
                               WHEN 'c' THEN 'composite' WHEN 'r' THEN 'range'
                               ELSE 'base' END
          FROM pg_type ty WHERE ty.oid = t.oid) END,
    'version', CASE WHEN $1 = 'extension' THEN
       (SELECT extversion FROM pg_extension WHERE oid = t.oid) END,
    'schema', CASE WHEN $1 = 'extension' THEN
       (SELECT n.nspname FROM pg_extension e
          JOIN pg_namespace n ON n.oid = e.extnamespace WHERE e.oid = t.oid) END,
    -- A function's identity is its argument types, not its name; the planner
    -- needs the full signature to emit a legal DROP.
    'signature', CASE WHEN $1 = 'function' THEN
       (SELECT p.oid::regprocedure::text FROM pg_proc p WHERE p.oid = t.oid) END,
    'returns', CASE WHEN $1 = 'function' THEN
       (SELECT PG_GET_FUNCTION_RESULT(p.oid) FROM pg_proc p WHERE p.oid = t.oid) END,
    'owner', CASE $1
       WHEN 'function' THEN (SELECT PG_GET_USERBYID(proowner) FROM pg_proc WHERE oid = t.oid)
       WHEN 'type' THEN (SELECT PG_GET_USERBYID(typowner) FROM pg_type WHERE oid = t.oid)
       WHEN 'schema' THEN (SELECT PG_GET_USERBYID(nspowner) FROM pg_namespace WHERE oid = t.oid)
       END,
    -- For a schema: what is still inside it. Dropping a non-empty schema is
    -- refused without CASCADE, and CASCADE here is the widest blast radius in
    -- the whole tool.
    'contains', CASE WHEN $1 = 'schema' THEN COALESCE((
       SELECT JSONB_AGG(c.relname ORDER BY c.relname)
         FROM pg_class c WHERE c.relnamespace = t.oid
          AND c.relkind IN ('r','p','v','m','S','f')), '[]'::jsonb) END)
  FROM target t WHERE t.oid IS NOT NULL),
  JSONB_BUILD_OBJECT('exists', false, 'kind', $1))
)SQL";

// Extensions that could be installed, with their versions -- so create_extension
// can refuse a name the server cannot satisfy rather than emitting a statement
// that fails, and can say which version it would get.
inline constexpr const char* kAvailableExtensionSql = R"SQL(
SELECT JSONB_BUILD_OBJECT(
  'available', EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = $1),
  'default_version', (SELECT default_version FROM pg_available_extensions
                       WHERE name = $1))
)SQL";

// Server-wide readings: the connection budget (spike S12) and how busy the
// server is right now. The application's OWN pool limit is the ceiling that
// actually matters and is invisible from here, so it is configuration; what
// this reports is the server's, plus enough to say so honestly.
inline const char* kServerObservationSql = R"SQL(
SELECT JSONB_BUILD_OBJECT(
  'max_connections', current_setting('max_connections')::int,
  'reserved_connections',
      current_setting('superuser_reserved_connections')::int
      + COALESCE(NULLIF(current_setting('reserved_connections', true), '')::int, 0),
  'current_backends', (SELECT COUNT(*) FROM pg_stat_activity),
  'active_backends', (SELECT COUNT(*) FROM pg_stat_activity WHERE state = 'active'),
  'ungranted_locks', (SELECT COUNT(*) FROM pg_locks WHERE NOT granted),
  'oldest_xact_age_s', (SELECT ROUND(EXTRACT(EPOCH FROM now() - MIN(xact_start))::numeric, 1)
                          FROM pg_stat_activity
                         WHERE xact_start IS NOT NULL AND pid <> pg_backend_pid()),
  -- Parallel worker capacity, which runs out long before connections do.
  --
  -- Measured on a stock 18.6: max_parallel_workers is 8 and
  -- max_parallel_maintenance_workers is 2. Thirty-two concurrent migrations
  -- each wanting a concurrent index build share those eight slots, and past
  -- them a build does not queue -- it silently falls back to single-threaded,
  -- and every duration the plan estimated is wrong with nothing reporting it.
  --
  -- 'parallel_workers_active' is the only live reading here; the rest are
  -- settings. There is NO cpu count available in SQL at all: the only
  -- cpu-named settings are planner cost constants, which is why host vCPUs is
  -- configuration in this tool exactly as it is in pg_licht.
  'max_worker_processes', CURRENT_SETTING('max_worker_processes')::int,
  'max_parallel_workers', CURRENT_SETTING('max_parallel_workers')::int,
  'max_parallel_maintenance_workers',
      CURRENT_SETTING('max_parallel_maintenance_workers')::int,
  'parallel_workers_active', (SELECT COUNT(*) FROM pg_stat_activity
                               WHERE backend_type = 'parallel worker'),
  -- pg_settings.setting, not current_setting(): the latter returns "256MB"
  -- with units and does not cast to a number.
  'maintenance_work_mem_kb', (SELECT setting::bigint FROM pg_settings
                               WHERE name = 'maintenance_work_mem'),
  'is_in_recovery', pg_is_in_recovery(),
  'now', now()
)
)SQL";

inline std::string strip_trailing_semicolon(const std::string& s) {
  auto end = s.find_last_not_of(" \n\t\r");
  if (end == std::string::npos) return {};
  if (s[end] == ';') {
    end = s.find_last_not_of(" \n\t\r", end == 0 ? 0 : end - 1);
    if (end == std::string::npos) return {};
  }
  return s.substr(0, end + 1);
}

}  // namespace detail

// How stale an estimate may be before it is worth paying AccessShareLock for a
// measured size. One hour, and only when the estimate is near a decision
// threshold -- see escalate_size below.
inline constexpr int kEstimateStalenessSeconds = 3600;

// Observation must never queue behind the very lock it is trying to report.
//
// pg_get_indexdef() opens the index relation and so takes AccessShareLock:
// measured 2026-09-05 on 18.6, it blocks outright behind an AccessExclusiveLock,
// while plain pg_class/pg_index/pg_attribute column reads and format_type() do
// not. Without a bound, observing a table mid-ALTER would hang for the length
// of the ALTER -- the planner's own measurement blocking on the thing it is
// planning around, which is the exact hazard documented for pg_table_size().
inline constexpr int kObservationLockTimeoutMs = 2000;

// SQLSTATE 55P03, lock_not_available. Matched by code because libpqxx declares
// no exception class for it -- the same rule the rest of this codebase follows:
// type where libpqxx has a class, SQLSTATE where it does not.
inline bool is_lock_not_available(const pqxx::sql_error& e) {
  return std::string(e.sqlstate()) == "55P03";
}

class Catalog {
 public:
  explicit Catalog(const ConnConfig& cfg, ConnectionCache* cache = nullptr)
      : cfg_(cfg), cache_(cache) {}

  // Gathers everything the planner needs for the tables a spec names.
  // Observes non-relation objects. `keys` are "kind:schema.name" or
  // "kind:name" for the unqualified ones (schema, extension).
  void observe_objects(ReadSession& s, Observations& obs,
                       const std::vector<std::string>& keys) {
    for (const auto& key : keys) {
      if (obs.objects.contains(key)) continue;
      const auto colon = key.find(':');
      if (colon == std::string::npos) continue;
      const auto kind = key.substr(0, colon);
      auto rest = key.substr(colon + 1);
      std::string schema, name;
      const auto dot = rest.find('.');
      if (dot == std::string::npos) {
        name = rest;
      } else {
        schema = rest.substr(0, dot);
        name = rest.substr(dot + 1);
      }
      const auto r = pqxx_exec(s.txn(), detail::kObjectObservationSql,
                               pqxx::params{kind, name, schema});
      if (!r.empty() && !r[0][0].is_null()) {
        obs.objects[key] = json::parse(r[0][0].as<std::string>());
      }
      if (kind == "extension") {
        const auto a = pqxx_exec(s.txn(), detail::kAvailableExtensionSql,
                                 pqxx::params{name});
        if (!a.empty() && !a[0][0].is_null()) {
          const auto avail = json::parse(a[0][0].as<std::string>());
          obs.objects[key]["available"] = avail.value("available", false);
          obs.objects[key]["default_version"] = avail.value("default_version", json());
        }
      }
    }
  }

  Observations observe(const std::vector<std::string>& schemas,
                       const std::vector<std::string>& tables,
                       const std::vector<std::string>& object_keys = {}) {
    if (schemas.size() != tables.size()) {
      throw std::runtime_error("observe: schema/table lists differ in length");
    }
    ReadSession s(cfg_, std::nullopt, cache_, kObservationLockTimeoutMs);
    Observations obs;
    obs.server_version = s.server_version();

    const auto server = s.txn().exec(detail::kServerObservationSql);
    if (!server.empty() && !server[0][0].is_null()) {
      obs.server = json::parse(server[0][0].as<std::string>());
    }
    obs.gathered_at = obs.server.value("now", json());
    observe_objects(s, obs, object_keys);

    for (std::size_t i = 0; i < schemas.size(); ++i) {
      const auto qualified = schemas[i] + "." + tables[i];
      if (obs.tables.contains(qualified)) continue;
      try {
        const auto r = pqxx_exec(s.txn(), detail::kTableObservationSql,
                                 pqxx::params{schemas[i], tables[i]});
        if (!r.empty() && !r[0][0].is_null()) {
          obs.tables[qualified] = json::parse(r[0][0].as<std::string>());
        }
      } catch (const pqxx::sql_error& e) {
        if (!is_lock_not_available(e)) throw;
        // Something holds a strong lock on this table right now. That is not a
        // failure to report -- it is the single most important thing to report,
        // because planning a migration against a table already under
        // AccessExclusiveLock is exactly what must not happen.
        obs.tables[qualified] = json{
            {"exists", true},
            {"observation_blocked", true},
            {"blocked_reason",
             "could not read " + qualified + " within " +
                 std::to_string(kObservationLockTimeoutMs) +
                 "ms: something holds a lock that conflicts with AccessShareLock "
                 "(an ALTER TABLE, a plain CREATE INDEX, a VACUUM FULL, or a "
                 "LOCK TABLE). Use pg_licht currentLocks to see what, and plan "
                 "again once it has finished."}};
        // The transaction is aborted after a failed statement, so a fresh one
        // is needed for whatever tables remain.
        s.txn().abort();
        s.renew();
      }
    }
    return obs;
  }

  // Proves a whole plan actually works, in a transaction that never commits.
  //
  // This is the property the project was conceived around: almost all
  // PostgreSQL DDL is transactional, so the earlier steps of a plan can be
  // APPLIED, the later steps checked against the schema they produce, and the
  // whole thing rolled back. Statement-by-statement checking cannot do this --
  // a backfill referencing a column that step 0 adds does not parse until step
  // 0 has run, and that is the ordinary case, not an edge one.
  //
  // Three honest costs, all bounded and all reported:
  //
  //  - It takes the real locks. An ALTER TABLE here takes AccessExclusiveLock,
  //    briefly, and rolls it back. lock_timeout bounds the attempt so a dry run
  //    can never queue behind anything, and it is the same lock the migration
  //    would take anyway -- but it IS a side effect of planning, so it is
  //    opt-outable and the result says whether it ran.
  //  - CREATE INDEX CONCURRENTLY cannot run inside a transaction block, so it
  //    is skipped and reported as unverified rather than silently passed.
  //  - The backfill is EXPLAINed, never executed. ANALYZE is never used.
  // COPY ... FROM STDIN, from a step's detail. Shared by the dry run and, in
  // spirit, by executor.h::run_copy -- pqxx::stream_to is the only sanctioned
  // way to send COPY data through libpqxx 7.10, and it builds the statement
  // itself, which is why the planner emits exactly the form it produces.
  // ONE implementation, called by the dry run here and by executor.h::run_copy.
  // There were two, differing in ways that were nobody's intent: one quoted
  // column names by concatenating a quote character, the other did the same a
  // few lines later, and the cell loop was written out twice. A COPY payload
  // is the one place where "what ran" is not entirely in the SQL, so the two
  // halves of the project that send one had better send it identically.
  //
  // `written` is a reference rather than a return value because the caller
  // needs the count even when this throws: a failed COPY records how many rows
  // had been handed to the stream before the server refused one.
  static void stream_copy(WriteSession& session, const json& detail,
                          long long& written) {
    std::vector<std::string> columns;
    for (const auto& c : detail.value("copy_columns", json::array())) {
      columns.push_back(pglaswell::detail::quote_identifier(c.get<std::string>()));
    }
    // copy_relation, not qualified: stream_to splices the path straight into
    // the COPY statement, so it has to be the quoted form.
    auto stream = pqxx::stream_to::raw_table(
        session.txn(),
        detail.value("copy_relation", detail.value("qualified", "")),
        pglaswell::detail::join(columns, ", "));
    for (const auto& row : detail.value("copy_rows", json::array())) {
      // Each cell as its own optional<string>: a JSON null becomes a real SQL
      // NULL rather than the four characters "null", which is the difference
      // between an absent value and a literal that happens to spell one.
      // Numbers and booleans go as their canonical text, which is what COPY's
      // text format expects and what the column's own type then parses.
      std::vector<std::optional<std::string>> cells;
      cells.reserve(row.size());
      for (const auto& cell : row) {
        if (cell.is_null()) cells.emplace_back(std::nullopt);
        else if (cell.is_string()) cells.emplace_back(cell.get<std::string>());
        else if (cell.is_boolean()) cells.emplace_back(cell.get<bool>() ? "true" : "false");
        else cells.emplace_back(cell.dump());
      }
      stream.write_row(cells);
      ++written;
    }
    stream.complete();
  }

  struct DryRun {
    bool ran = false;
    std::vector<std::string> problems;
    std::vector<int> unverified_steps;  // could not be included, or not reached
    std::string skipped_reason;
    int timed_out_at = -1;
    bool depends_on_skipped = false;
  };

  // `copy_payloads` is parallel to `steps`: a null entry for an ordinary step,
  // and for a copy_rows step the {copy_columns, copy_rows, qualified} detail its
  // rows travel in. COPY is the one statement whose work is not entirely in its
  // SQL, so a dry run that only had the statement could not check it at all --
  // and skipping it would leave the column count, the types and every
  // constraint on the table unverified, which is most of what a COPY can get
  // wrong. Streamed for real here, inside the transaction that is rolled back.
  DryRun dry_run(const std::vector<std::pair<int, std::vector<std::string>>>& steps,
                 const std::vector<bool>& txn_forbidden, int server_version,
                 const std::vector<json>& copy_payloads = {}) {
    DryRun out;
    WriteSession w(cfg_);
    // A dry run must never queue: it holds strong locks, and a planning call
    // that blocks the application is worse than one that declines to check.
    ConnConfig probe = cfg_;
    probe.executor.lock_timeout_ms = kObservationLockTimeoutMs;
    // The dry run runs the whole plan in one transaction, so a scanning step
    // holds every lock the steps before it took. Bounded so a planning call
    // can never block writes for the length of a scan: correctness is what a
    // dry run proves, and it does not need to finish the work to prove it.
    probe.statement_timeout_ms = cfg_.executor.dry_run_statement_timeout_ms;
    WriteSession session(probe);

    try {
      session.begin("pg_laswell/dry-run (rolled back)");
    } catch (const std::exception& e) {
      out.skipped_reason = std::string("could not open a dry-run transaction: ") + e.what();
      return out;
    }

    out.ran = true;
    // Once a step has been skipped, anything after it may depend on what that
    // step would have created -- a partitioned index recipe attaches the child
    // indexes its skipped concurrent builds would have made. A failure after a
    // skip is therefore a gap the DRY RUN created, not a defect in the plan,
    // and reporting it as a problem would send someone hunting for a fault
    // that is not there.
    bool skipped_any = false;
    for (std::size_t i = 0; i < steps.size(); ++i) {
      if (txn_forbidden[i]) {
        out.unverified_steps.push_back(steps[i].first);
        skipped_any = true;
        continue;
      }
      if (i < copy_payloads.size() && copy_payloads[i].is_object()) {
        try {
          long long sent = 0;
          stream_copy(session, copy_payloads[i], sent);
        } catch (const pqxx::sql_error& e) {
          out.problems.push_back(
              "step " + std::to_string(steps[i].first) + " (COPY): " + e.what());
          break;
        }
        continue;
      }
      for (const auto& raw : steps[i].second) {
        const auto stmt = detail::strip_trailing_semicolon(raw);
        if (stmt.empty()) continue;
        const auto head = stmt.substr(0, stmt.find_first_of(" \n"));
        const bool is_query =
            stmt.rfind("WITH", 0) == 0 || head == "UPDATE" || head == "INSERT" ||
            head == "SELECT" || head == "DELETE" || head == "MERGE";
        try {
          if (is_query) {
            // GENERIC_PLAN (PG16+) plans a statement with $1/$2 placeholders
            // without binding values. On older servers PREPARE catches the
            // same class of error. Never ANALYZE: EXPLAIN must not execute the
            // thing being planned.
            if (server_version >= 160000) {
              session.txn().exec("EXPLAIN (GENERIC_PLAN, FORMAT JSON) " + stmt);
            } else {
              session.txn().exec("PREPARE laswell_dry AS " + stmt);
              session.txn().exec("DEALLOCATE laswell_dry");
            }
          } else {
            session.txn().exec(stmt);  // real DDL, rolled back below
          }
        } catch (const pqxx::sql_error& e) {
          // A statement timeout is not a defect in the plan -- it means this
          // step does real work that a dry run declines to finish. Everything
          // from here on is simply unverified, and saying so beats reporting a
          // problem that does not exist.
          if (std::string(e.sqlstate()) == "57014") {
            out.timed_out_at = steps[i].first;
            for (std::size_t k = i; k < steps.size(); ++k) {
              out.unverified_steps.push_back(steps[k].first);
            }
            session.rollback();
            return out;
          }
          if (skipped_any) {
            out.unverified_steps.push_back(steps[i].first);
            out.depends_on_skipped = true;
            session.rollback();
            return out;
          }
          out.problems.push_back("step " + std::to_string(steps[i].first) + ": " +
                                 e.what());
          session.rollback();
          return out;
        }
      }
    }
    // Always. Nothing a dry run does is ever committed.
    session.rollback();
    return out;
  }

  // Escalates one table to a measured size.
  //
  // Kept out of observe() and out of the planner entirely. pg_table_size() is
  // not a physical read -- it stat()s one file per segment -- but it opens the
  // relation with AccessShareLock, so on a table being rewritten by an ALTER
  // TABLE it waits behind AccessExclusiveLock. Paying that unconditionally
  // would mean the planner's own measurement could block on the thing it is
  // trying to plan around.
  void escalate_size(Observations& obs, const std::string& schema,
                     const std::string& table) {
    ReadSession s(cfg_, std::nullopt, cache_);
    const auto r = pqxx_exec(
        s.txn(),
        "SELECT JSONB_BUILD_OBJECT("
        "  'size_measured', pg_table_size(c.oid),"
        "  'indexes_size', pg_indexes_size(c.oid),"
        "  'total_size', pg_total_relation_size(c.oid))"
        "  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace"
        " WHERE n.nspname = $1 AND c.relname = $2",
        pqxx::params{schema, table});
    const auto qualified = schema + "." + table;
    if (!r.empty() && !r[0][0].is_null() && obs.tables.contains(qualified)) {
      const auto measured = json::parse(r[0][0].as<std::string>());
      for (auto it = measured.begin(); it != measured.end(); ++it) {
        obs.tables[qualified][it.key()] = it.value();
      }
    }
  }

 private:
  ConnConfig cfg_;
  ConnectionCache* cache_ = nullptr;
};

}  // namespace pglaswell
